name       : caja-extensions
version    : 1.18.2
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/caja-extensions-1.18.2.tar.xz : 6aa9e7da54c1e660eb714a934654cd7d44303a7d4df7be5d2ee3fe337d1bb218
license    : GPL-2.0
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
    - gtk-doc
    - mate-common
setup      : |
    ./autogen.sh %CONFOPTS% --with-gtk=3.0 --enable-gksu=no
build      : |
    %make
install    : |
    %make_install
