name       : caja-extensions
version    : 1.20.1
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.20/caja-extensions-1.20.1.tar.xz : 7610931d4a3135f2f3b88551652907e4ef25c48b3f18c8e83ecd65c3df606706
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - gtk-doc
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
setup      : |
    %configure --enable-gksu=no
build      : |
    %make
install    : |
    %make_install
