name       : caja-extensions
version    : 1.18.1
release    : 3
source     :
    - https://pub.mate-desktop.org/releases/1.18/caja-extensions-1.18.1.tar.xz : bcb2f355c883bdca06a28028ca9a832d84e693257a60ea24304abbf98fa2ea41
license    : GPL-2.0
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
    - gtk-doc
    - mate-common
setup      : |
    ./autogen.sh %CONFOPTS% --with-gtk=3.0 --enable-gksu=no
build      : |
    %make
install    : |
    %make_install
