name       : caja-extensions
version    : 1.22.0
release    : 9
source     :
    - https://github.com/mate-desktop/caja-extensions/archive/v1.22.0.tar.gz : b12db588c7673368403048de395b6eff082c4981524b1e291a4f1b96a7870bc0
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
    - mate-common
setup      : |
    %autogen --enable-gksu=no --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
