name       : caja-extensions
version    : 1.22.1
release    : 11
source     :
    - https://github.com/mate-desktop/caja-extensions/archive/v1.22.1.tar.gz : 6d6b283d3278ee4e55135461a79d4e2d1b2820bf0ae04869891b844296713c98
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
    - mate-common
setup      : |
    %autogen --enable-gksu=no --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
