name       : caja-extensions
version    : 1.20.0
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.20/caja-extensions-1.20.0.tar.xz : f2b65081ddbe9062c5a6ee1e00b6433b43a4c7aaeb90e34047fbf41a863e71a9
license    : GPL-2.0
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - gtk-doc
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
setup      : |
    %configure --enable-gksu=no
build      : |
    %make
install    : |
    %make_install
