name       : caja-extensions
version    : 1.20.2
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/caja-extensions-1.20.2.tar.xz : 1f37efa2a43fecfa32ae262a4a12988423c37046b2b28d7fe3c6be3746eb8193
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Set of extensions for Caja, the MATE file manager.
description: |
    Set of extensions for Caja, the MATE file manager.
builddeps  :
    - gtk-doc
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gupnp-1.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(mate-desktop-2.0)
setup      : |
    %configure --enable-gksu=no
build      : |
    %make
install    : |
    %make_install
